# -*- coding: utf-8 -*-
"""summary_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OoLH3chvS4woSQB6kO3GIX4a9FjeCJE5
"""

import random

def generate_summary(job_title, experience, skills):
    exp_count = len(experience)
    if exp_count == 0:
        exp_text = "no professional experience yet"
    elif exp_count == 1:
        exp_text = "1 year of experience"
    else:
        exp_text = f"{exp_count}+ years of experience"

    top_skills = skills[:3] if skills else ["problem-solving", "teamwork"]

    skills_text = ", ".join(top_skills)

    recent_role = ""

    if experience:
        last_job = experience[-1]

        role = last_job.get("role", "professional")
        company = last_job.get("company", "a company")

        recent_role = f"Most recently worked as {role} at {company}."

    openings = [
        f"Motivated {job_title} with {exp_text}.",
        f"Results-driven {job_title} bringing {exp_text}.",
        f"Dedicated {job_title} with a strong foundation in modern technologies and {exp_text}."
    ]

    skill_lines = [
        f"Skilled in {skills_text}.",
        f"Experienced with {skills_text} in real-world projects.",
        f"Strong expertise in {skills_text}."
    ]

    closings = [
        "Eager to contribute to innovative teams and build impactful solutions.",
        "Passionate about solving complex problems with technology.",
        "Looking to apply technical skills in challenging environments."
    ]

    summary = (
        random.choice(openings) + " " +
        recent_role + " " +
        random.choice(skill_lines) + " " +
        random.choice(closings)
    )

    return summary